### ISSUE TITLE
Cube Analytics page throws "e is undefined" error

### ISSUE THREAD

**Issue by rudyards** [CubeArtisan/cubeartisan#202]
**Describe the bug**
For [this custom cube](https://cubeartisan.net/cube/mrv/analytics?tab=5), the analytics page shows an error rather than the expected list of cards and their ELOs. I suspect it has something to do with the fact that the cube is almost entirely custom named/given custom costs and so on. 

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Firefox

**Additional context**

**Comment by ruler501** [comment]
@rudyards can you check if it's fixed now. I am able to pull up the playtest data (note since it tracks by name it probably isn't super useful)

**Comment by rudyards** [comment]
Confirmed that this is fixed (the page loads and all canon cards appear).

I do wonder if we could just use the card's original name/ID to look up things in analytics, but I'll put time into that at some other point.
