### ISSUE TITLE
When A Card Is Dragged, It Links You To The Full Card Image

### ISSUE THREAD

**Issue by rudyards** [CubeArtisan/cubeartisan#203]
As a user, when I drag a card, I expect it to just move. Dragging behavior is different from clicking. In practice, it will move to the new spot, and then take you to the card's image directly, and you have to hit the back button to return to whatever draft or deckbuilding you're in.

**Comment by ruler501** [comment]
Is this on Firefox?

**Comment by rudyards** [comment]
Yep, on firefox. Forgot to verify that this works as intended on Chrome. Also works as intended on Safari.

**Comment by rudyards** [comment]
So this is a duplicate of #62 and can be closed.
