### ISSUE TITLE
Add The Ability To Specify Custon Names When Importing From CSV

### ISSUE THREAD

**Issue by rudyards** [CubeArtisan/cubeartisan#204]
**What would you like to be able to do?**
I, as a user, would like the ability to specify a card's custom name in addition to the other details about it (cmc, type, etc) when doing a bulk upload from a csv.

**Describe how you would use the feature**
When uploading a csv, a user may specify a card's custom name in a column of a CSV. If no name is provided, it uses the default name as expected.

**Additional context**
This feature is a key step in allowing users to more easily bulk upload custom sets/custom cubes.

**Comment by ruler501** [comment]
This requires another way to look up the card object backing it though. I'll have to think of the best way to integrate it. The problem is that we need to identify a unique card to use as the base for the card. Once the mtg.design apis are done I'll probably migrate to using id's in the CSV as the default indicator. I'm open to suggestions on how the CSV should work. One important restriction is that it needs to be compatible with CubeCobra to enable importing from and exporting to them.

**Comment by rudyards** [comment]
To clarify my original thought, since I think there's less work here than it looks:

The custom name would be **in addition** to currently required details (such as canon card). This would allow us to keep the "real" card present for ease of importing and exporting. The request here is fundamentally just to remove the hassle of having to go to every single card and assign them a custom name. 

I'll try and tackle a proposed version of this after work tomorrow.

**Comment by rudyards** [comment]
I confirmed that adding a column for Override Names would be non destructive to people's abilities to import to CubeCobra, so even if that was part of our csv export, that wouldn't be an issue.

I do now see what you were saying about how name is handled. One possible approach would be adding a line in `cubefn.js` around line 264 that was "overrideName", and then adding this around line 174 in `import.js`

```
if (card.overrideName) {

              card.name = card.overrideName;

}
```

This way it is after we've done the lookup to confirm the card's base identity and set the details properly.

It's possible this doesn't work with the current implementation of changelog, however? Or that there is some other issue I'm not seeing immediately.
